version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root         
      POSTGRES_PASSWORD: 12345_Ulkar
      POSTGRES_DB: mydb               # Set the default database name
    ports:
      - "5432:5432"                   # Map the PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data

volumes:
  postgres_data:

